name: Tests

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ '3.12' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python }}
          cache: true

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install --yes libgl1-mesa-dev
          pdm install --check --dev

      - name: Test with pytest
        run: |
          pdm run make test-cicd

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sysid/inka2

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python }}
          cache: true

      - name: Install dependencies
        run: |
          pdm install --check --dev

      - name: mypy
        run: |
          pdm run mypy --python-version=3.12 src/

      - name: lint
        run: |
          pdm run make lint

      - name: format
        run: |
          pdm run make format-check

      - name: isort
        run: |
          pdm run isort . --check --diff
